config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]

  get 'user_info/edit'

  post 'user_info/update'

  get 'addresses/get_user_address'

  get 'addresses/get_addresses_near_user'

  resources :boards
  resources :agreements, except: [:show]
  post 'agreements/:id/agree' => 'agreements#agree', as: :agreements_agree
  resources :message, only: [:new, :create, :destroy]

  authenticated :user do
    root :to => 'profile#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  get 'profile' => 'profile#index'

  post '/skill/add_skill_to_user' => 'skills#add_skill_to_user'
  post '/skill/kill_destroy' => 'skills#kill_destroy'
  delete '/skill/kill_destroy' => 'skills#kill_destroy'
  delete '/admin/destroy_user' => 'admin#destroy_user'
 
  post '/skill/create_skill' => 'skills#create_skill'

  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  scope :user do
    resources :skills do
      get 'delete'
    end
  end

  get 'kill' => 'skills#kill'
  get 'create_new_skill' => 'skills#create_new_skill'

  match ':controller(/:action(/:id))', :via => :get

end

app/views/admin/_board_index.html.erb
<div id="boards">
   <%= render 'boards' %>
</div>

app/views/admin/_boards.html.erb
<div class="col-md-6">
  </br>
  <%= form_tag admin_index_path, :method => 'get', :class => 'form' do %>
      <p>
        <%= hidden_field_tag "tab", "boards" %>
        <%= text_field_tag :search, params[:search], class: 'admin-search form-control' %>
        <span class="pull-right"><%= submit_tag "Search", :name => nil, class: 'btn' %></span>
      </p>
  <% end %>
  <%= will_paginate @boards, renderer: BootstrapPagination::Rails %>
  <table class="table">
      <thead>
      <tr>
        <th>Id</th>
        <th>Details</th>
        <th>Skill Needed</th>
        <th>Skills Offered</th>
        <th>Status</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
          <% @boards.each do |b| %>
            <tr>
              <td><%= b.id %></td>
              <td><%= b.details %></td>
              <td><%= b.skill_needed %></td>
              <td><%= b.skills_offered %></td>
              <td><%= b.status %></td>
              <td>
                <div class="btn-group">
                  <%= link_to ("<i class='glyphicon glyphicon-remove'></i>").html_safe, board_path(b.id, :return_admin => true, :tab_redirect => 'boards'), method: :delete, data: {confirm: "Are you sure you want to remove this?"}  -%>
                </div>
              </td>
            </tr>
          <%- end -%>
      </tbody>
  </table>
  </br>
  <%= will_paginate @boards, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/_skill_index.html.erb
<div id="skills">
  <%= render 'skills' %>
</div>

app/views/admin/_skills.html.erb
<div class="col-md-6">
  </br>
  <%= form_tag admin_index_path, :method => 'get', :class => 'form' do %>
      <p>
        <%= hidden_field_tag "tab", "skills" %>
        <%= text_field_tag :search, params[:search], class: 'admin-search form-control' %>
        <span class="pull-right"><%= submit_tag "Search", :name => nil, class: 'btn' %></span>
      </p>
  <% end %>
  <%= will_paginate @skills, renderer: BootstrapPagination::Rails %>
  <table class="table">
    <thead>
    <tr>
      <th>Skill</th>
      <th>Details</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @skills.each do |s| %>
        <tr>
          <td><%= s.name %></td>
          <td>
            <div class="btn-group">
              <%= link_to ("<i class='glyphicon glyphicon-remove'></i>").html_safe, { controller: 'skills', action: 'kill_destroy', id: s.id,
                                                                                      return_admin: true, tab_redirect: 'skills' }, method: :delete,
                          data: { confirm: "Are you sure?" } %>
            </div>
          </td>
        </tr>
    <%- end -%>
    </tbody>
  </table>
  <%= link_to 'Add New', create_new_skill_path, return_admin: true, tab_redirect: 'skills', remote: true, class: 'btn btn-warning btn-xs' %>
  </br>
  <%= will_paginate @skills, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/_user_index.html.erb
<div id="users">
  <%= render 'users' %>
</div>

app/views/admin/_users.html.erb
<div class="col-md-6">
  </br>
  <%= form_tag admin_index_path, :method => 'get', :class => 'form' do %>
      <p>
        <%= hidden_field_tag "tab", "users" %>
        <%= text_field_tag :search, params[:search], class: 'admin-search form-control'%>
        <span class="pull-right"><%= submit_tag "Search", :name => nil, class: 'btn' %></span>
      </p>
  <% end %>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
  <table class="table">
    <thead>
    <tr>
      <th>Email</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |u| %>
        <tr>
          <td><%= u.email %></td>
          <td>
            <div class="btn-group">
              <p><%= link_to ("<i class='glyphicon glyphicon-remove'></i>").html_safe, {id: u.id, controller: 'admin', action: 'destroy_user', tab_redirect: 'users', admin_redirect: true }, data: { confirm: "Are you sure?" }, method: :delete %></p>
            </div>
          </td>
        </tr>
    <%- end -%>
    </tbody>
  </table>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1>Admin Dashboard</h1>
    </div>
  </div>
</div>
<div class="container">
  <div>

    <!-- Nav tabs -->
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#users" aria-controls="users" role="tab" data-toggle="tab">Users</a></li>
      <li role="presentation"><a href="#skills" aria-controls="skills" role="tab" data-toggle="tab">Skills</a></li>
      <li role="presentation"><a href="#boards" aria-controls="boards" role="tab" data-toggle="tab">Boards</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="users">
        <div class="row">
          <%= render 'user_index' %>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="skills">
        <div class="row">
          <div class="skill-user-index">
            <%= render 'skill_index' %>
          </div>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="boards">
        <div class="row">
          <%= render 'board_index' %>
        </div>   
      </div>
    </div>
  </div> 
</div>

<% if params[:tab_redirect] == 'users'  || params[:tab] == 'users' %>
    <script>
        $('#myTabs a[href="#users"]').tab('show')
    </script>
<% elsif params[:tab_redirect] == 'skills'  || params[:tab] == 'skills' %>
    <script>
        $('#myTabs a[href="#skills"]').tab('show')
    </script>
<% elsif params[:tab_redirect] == 'boards'  || params[:tab] == 'boards'  %>
    <script>
        $('#myTabs a[href="#boards"]').tab('show')
    </script>
<% else %>
    <script>
        $('#myTabs a[href="#users"]').tab('show')
    </script>
<% end %>

<div id="skill-user-modal" class="modal fade">
   <div class="modal-dialog container">
     <div id="inner-skill-user-modal" class="modal-content row"></div>
   </div>
</div>

app/views/admin/index.js.erb
if ($('#users').hasClass("active")) {
    $("#users").html("<%= escape_javascript(render("users")) %>");
} else if ($('#skills').hasClass("active")) {
    $("#skills").html("<%= escape_javascript(render("skills")) %>");
} else if ($('#boards').hasClass("active")) {
    $("#boards").html("<%= escape_javascript(render("boards")) %>");
} else {
    $("#users").html("<%= escape_javascript(render("users")) %>");
}