config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]

  get 'user_info/edit'

  post 'user_info/update'

  get 'addresses/get_user_address'

  get 'addresses/get_addresses_near_user'

  resources :boards
  resources :agreements, except: [:show]
  post 'agreements/:id/agree' => 'agreements#agree', as: :agreements_agree
  resources :message, only: [:new, :create, :destroy]

  authenticated :user do
    root :to => 'profile#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  get 'profile' => 'profile#index'

  post '/skill/add_skill_to_user' => 'skills#add_skill_to_user'
  post '/skill/kill_destroy' => 'skills#kill_destroy'
  delete '/skill/kill_destroy' => 'skills#kill_destroy'
  delete '/admin/destroy_user' => 'admin#destroy_user'
 
  post '/skill/create_skill' => 'skills#create_skill'

  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  scope :user do
    resources :skills do
      get 'delete'
    end
  end

  get 'kill' => 'skills#kill'
  get 'create_new_skill' => 'skills#create_new_skill'

  match ':controller(/:action(/:id))', :via => :get

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates_presence_of :name

  has_many :users, through: :skills_users
  has_many :skills_users

  def self.search(search)
    if search
      if search == ""
        all.order('name ASC')
      else
        where("lower(name) LIKE ?", "%#{search.downcase}%").order('name ASC')
      end
    else
      all
    end
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  respond_to :html, :js

  def add_skill_to_user
    @skill = Skill.find(params[:name])
    @details = params[:details]

    @skills_user = SkillsUser.create(user_id: current_user.id, skill_id: @skill.id, details: @details )
    redirect_to skills_path(@skills_user.id)
  end

  def new
    @skills = Skill.all
    @skills_user = SkillsUser.new
  end

  def index
    @skills_users = current_user.skills_users
  end

  def show
    current_user.skills_users.find(params[:id])
  end

  def delete
    @skills_user = current_user.skills_users.find(params[:skill_id])
  end

  def destroy
    current_user.skills_users.destroy(params[:id])
    @skills_users = current_user.skills_users
  end


  def edit
    @skills = Skill.all
    @skills_user = SkillsUser.find(params[:id])
  end

  def update
    @skills_user = SkillsUser.find(params[:id])
    @skills_user.update(details: params[:details])
    redirect_to skills_path
  end

  def kill
    @skills = Skill.all
  end

  def kill_destroy
    @skills_user = SkillsUser.where(skill_id: params[:id]).delete_all
    @skill = Skill.destroy(params[:id])
    if @skill.save
      if params[:return_admin]
        flash[:primary] = 'You destroyed a skill'
        redirect_to admin_index_path(:tab_redirect => params[:tab_redirect])
      else
        redirect_to skills_path
      end
    end   
  end

  def create_new_skill
    @skill = Skill.new
  end

  def create_skill
    @skill = Skill.create(name: params[:name])
    if @skill.save
      if params[:return_admin]
        flash[:primary] = 'You created a new skill'
        redirect_to admin_index_path(:tab_redirect => params[:tab_redirect])
      else
      redirect_to admin_index_path
      end
    end
  end

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_delete.html.erb
<div class="modal-header">
  <h3>Delete skill on profile</h3>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you want to remove <strong><%= @skills_user.skill.name %></strong> from your list of skills?
</div>
<div class="modal-footer">
  <%= link_to 'Yes delete this skill?', skill_path(@skills_user), method: :delete, remote: true, class: 'btn btn-danger' %>
  <%= link_to 'No please don\'t', "#", class: 'btn btn-default', data: { dismiss: "modal" } %>
</div>

app/views/skills/_edit.html.erb
<div class="modal-header">
  <h3>Edit Skill: <%= @skills_user.skill.name %> Details</h3>
</div>
<%= render 'form_edit' %>

app/views/skills/_form_edit.erb
<%= form_tag(skill_path(@skills_user), method: :put, id: params[:id]) %>
<div class="col-md-8 col-md-offset-2 top-20 bottom-20">
  <div class="form-group">
    <span><label for="">Details</label></span>
    <span><%= text_area_tag :details, @skills_user.details, class: 'form-control' %></span>
  </div>
  <span><%= submit_tag 'Update Skill', class: 'btn btn-primary' %></span>
</div>

app/views/skills/_form_kill.html.erb
<%= form_tag({controller: :skill, action: :kill_destroy}, method: :post) %>
<div class="col-md-8 col-md-offset-2 top-20 bottom-20">
  <div class="form-group">
    <label for="">Select a skill</label>
    <span><%= select_tag :name, options_from_collection_for_select( @skills, 'id', 'name', '1') %></span>
  </div>
  <span><%= submit_tag 'Destroy Skill Forever', class: 'btn btn-primary' %></span>
</div>

app/views/skills/_form_new_skill.html.erb
<%= form_tag({controller: :skill, action: :create_skill, return_admin: true, tab_redirect: 'skills'}, method: :post) %>
<div class="col-md-8 col-md-offset-2 top-20 bottom-20">
  <div class="form-group">
    <%= label_tag 'name' %>
    <span><%= text_field_tag :name  %></span>
  </div>
  <span><%= submit_tag 'Create', class: 'btn btn-primary' %></span>
</div>

app/views/skills/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <table class="table">
        <thead>
          <tr>
            <th>Skill</th>
            <th>Details</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @skills_users.each do |s| %>
          <tr>
            <td><%= s.skill.name %></td>
            <td><%= s.details %></td>
            <td>
              <div class="btn-group">
                <%= link_to 'Edit', edit_skill_path(s.id), remote: true, class: 'btn btn-warning btn-xs' %>
                <%= link_to 'Delete', skill_delete_path(s.id), remote: true, class: 'btn btn-danger btn-xs' %>
              </div>
            </td>
          </tr>
        <%- end -%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/skills/_new.html.erb
<div class="modal-header">
  <h3>Tell us a skill that you have</h3>
</div>
<%= render 'form_add' %>

app/views/skills/_new_skill.html.erb
<div class="modal-header">
  <h3>Create a new skill</h3>
</div>
<%= render 'form_new_skill' %>

app/views/skills/_save.js.erb
    $('.skill-user-index').html("<%= escape_javascript(render 'index') %>")
    $('#skill-user-modal').modal('hide')

app/views/skills/delete.js.erb
$("#inner-skill-user-modal").html("<%= escape_javascript(render 'delete') %>")
$("#skill-user-modal").modal("show")

app/views/skills/destroy.js.erb
<%= render 'save' %>

app/views/skills/edit.js.erb
$('#inner-skill-user-modal').html("<%= escape_javascript(render 'edit') %>")
$('#skill-user-modal').modal('show')

app/views/skills/kill.js.erb
$('#inner-skill-user-modal').html("<%= escape_javascript(render 'kill') %>")
$("#skill-user-modal").modal("show")

app/views/skills/new_skill.js.erb
$('#inner-skill-user-modal').html("<%= escape_javascript(render 'new_skill') %>");
$("#skill-user-modal").modal("show");