config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]

  get 'user_info/edit'

  post 'user_info/update'

  get 'addresses/get_user_address'

  get 'addresses/get_addresses_near_user'

  resources :boards
  resources :agreements, except: [:show]
  post 'agreements/:id/agree' => 'agreements#agree', as: :agreements_agree
  resources :message, only: [:new, :create, :destroy]

  authenticated :user do
    root :to => 'profile#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  get 'profile' => 'profile#index'

  post '/skill/add_skill_to_user' => 'skills#add_skill_to_user'
  post '/skill/kill_destroy' => 'skills#kill_destroy'
  delete '/skill/kill_destroy' => 'skills#kill_destroy'
  delete '/admin/destroy_user' => 'admin#destroy_user'
 
  post '/skill/create_skill' => 'skills#create_skill'

  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  scope :user do
    resources :skills do
      get 'delete'
    end
  end

  get 'kill' => 'skills#kill'
  get 'create_new_skill' => 'skills#create_new_skill'

  match ':controller(/:action(/:id))', :via => :get

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_one :message_thread, as: :discussable
  has_many :agreements

  def user_full_street_address
    a = self.user.addresses[0]
    "#{a.street_address} #{a.city}, #{a.state} #{a.zip}"
  end

  geocoded_by :user_full_street_address

  after_validation :geocode, if: ->(obj){ obj.user.addresses[0].street_address.present? and obj.user.addresses[0].street_address_changed? }

  validates :user_id, :skill_needed, :skills_offered, :status, :needed_by, presence: true
  validate :validate_skill_needed
  validate :validate_skills_offered
  validate :validates_needed_by

  def validate_skill_needed
    if !skill_needed.is_a? Array || skill_needed.count != 1
      errors.add(:skill_needed, :invalid)
    elsif !Skill.pluck(:name).include?(skill_needed[0])
      errors.add(:skill_needed, :invalid)
    end
  end

  def validate_skills_offered
    if !skills_offered.is_a? Array || skills_offered.count > 0
      errors.add(:skills_offered, :invalid)
    else
      skills = Skill.pluck(:name)
      skills_offered.each do |skill|
        errors.add(:skills_offered, :invalid) unless skills.include? skill
      end
    end
  end

  def validates_needed_by
    errors.add(:needed_by, :invalid) if needed_by.past?
  end

  def self.search(search)
    if search
      if search == ""
        all
      else
        where("lower(details->>'email') LIKE ? OR lower(details->>'city') LIKE ? OR array_to_string(skill_needed, ', ') LIKE ? OR array_to_string(skills_offered, ', ') LIKE ? OR lower(status) LIKE ?", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%")
      end
    else
      all
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user || nil
    @skills = Skill.all.pluck(:name)
    if params[:skill_needed] && params[:skill_offered]
      sn, so = params[:skill_needed], params[:skill_offered]
      if sn != 'none' && so == 'none'
        @board = Board.where('status = :status and :skill_needed = ANY (skill_needed)',
                             {status: 'awaiting', skill_needed: params[:skill_needed], skill_offered: params[:skill_offered]})
      elsif sn =='none' && so != 'none'
        @board = Board.where('status = :status and :skill_offered = ANY (skills_offered)',
                             {status: 'awaiting', skill_needed: params[:skill_needed], skill_offered: params[:skill_offered]})
      else
        @board = Board.where(status: 'awaiting')
      end
    else
      @board = Board.where(status: 'awaiting')
    end
  end

  def show
    @board = Board.find(params[:id])
    @thread = @board.message_thread
    @messages = Message.joins(:user_info).select(:text, :user_id, :first_name, :last_name, :created_at, 'md5("users"."email")').where(message_thread_id: @thread.id)
    @user_id = current_user.id
    @user_name = current_user.user_info.first_name
  end

  def new
    @board = Board.new
    @skills = Skill.all.pluck(:name)
  end

  def create
    skills_offered = []
    params.keys.each do |item|
      if item.include? '::'
        skills_offered << Skill.find(item.split('::')[1].to_i).name if params[item] == 'on'
      end
    end
    @board = Board.create(user_id: current_user.id, skill_needed: [params[:skill_needed]], skills_offered: skills_offered, details: {city: '', email: ''}, needed_by: Date.civil(params[:needed_by][:year].to_i, params[:needed_by][:month].to_i, params[:needed_by][:day].to_i))
    if @board.save
      @thread = MessageThread.create(title: "#{current_user.user_info.first_name} Item Discussion")
      @thread.update_attribute :discussable, @board
      if params[:details]
        Message.create(user_id: current_user.id, message_thread_id: @thread.id, text: params[:details])
      end
      redirect_to root_path
    else
      @skills = Skill.all.pluck(:name)
      render :new
    end
  end

  def edit
    @board = Board.find(params[:id])
    @skills = Skill.all.pluck(:name)
    @user = current_user
  end

  def update
    skills_offered = []
    params.keys.each do |item|
      p item
      if item.include? '::'
        skills_offered << Skill.find(item.split('::')[1].to_i).name if params[item] == 'on'
      end
    end
    @board = Board.find(params[:id])
    @board.update(skill_needed: [params[:skill_needed]], skills_offered: skills_offered, details: {}, needed_by: Date.civil(params[:needed_by][:year].to_i, params[:needed_by][:month].to_i, params[:needed_by][:day].to_i))
    if @board.save
      unless @board.message_thread
        @thread = MessageThread.create(title: "#{current_user.user_info.first_name} Item Discussion")
        @thread.update_attribute :discussable, @board
      end
    end

    redirect_to board_path(@board)
  end

  def destroy
    @board = Board.find(params[:id])
    @board.status = 'removed'
    if @board.save
      if params[:return_admin]
        flash[:success] = 'You destroyed a board'
        redirect_to admin_index_path(:tab_redirect => params[:tab_redirect])
      else
        redirect_to boards_path
      end
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def format_skills_offered skills_offered
    s = ''
    case skills_offered.count
      when 0
        s = 'nothing'
      when 1
        s = skills_offered[0]
      when 2
        s = "#{skills_offered[0]} or #{skills_offered[1]}"
      else
        skills_offered.each_with_index do |v, i|
          if i == skills_offered.count - 1
            s += "or #{v}"
          else
            s += "#{v}, "
          end
        end
    end
    s
  end
end

app/views/boards/_form.html.erb
<fieldset class="col-md-6">
  <% @board.errors.each do |error| -%>
    <p><%= error -%></p>
  <%- end -%>
  <div class="form-group col-md-6">
    <label for="">Needing</label><br/>
    <%- if @board.skill_needed[0] -%>
      <%= select_tag :skill_needed, options_for_select(@skills, @board.skill_needed[0]) %>
    <%- else -%>
      <%= select_tag :skill_needed, options_for_select(@skills) %>
    <%- end -%>
  </div>
  <div class="form-group col-md-6">
    <label for="">Offering</label>
    <%- current_user.skills.each do |s| -%>
      <div class="checkbox">
        <label>
          <input name="skill::<%= s.id -%>" type="checkbox" <%- if @board.skills_offered.include?(s.name) -%> checked <%- end -%>> <%= s.name -%>
        </label>
      </div>
    <%- end -%>
  </div>
  <div class="form-group col-md-6">
    <label for="">When do you need this?</label><br/>
    <%- if current_page? new_board_path -%>
      <%= select_date 30.days.from_now, prefix: :needed_by %>
    <%- else -%>
      <%= select_date @board.needed_by, prefix: :needed_by -%>
    <%- end -%>
  </div>
  <%- unless @board.id -%>
    <div class="form-group col-md-12">
      <label for="deatils">Details</label>
      <textarea name="details" id="" class="form-control" rows="5"></textarea>
    </div>
  <%- end -%>
  <div class="col-md-12">
    <% if current_user.sign_in_count == 1 && current_user.boards.count == 0  %>
      <input type="submit" class="btn btn-primary animated infinite pulse" value="Next"/>
      <%= link_to "Skip", root_path, class: "btn btn-primary", method: "get" %>
    <% else %>
      <input type="submit" value="Ok" class="btn btn-primary"/>
    <% end %>
  </div>
</fieldset>

app/views/boards/destroy.html.erb
<h1>Board#destroy</h1>
<p>Find me in app/views/board/destroy.html.erb</p>

app/views/boards/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1>Edit Your Board Entry</h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= form_tag({controller: 'boards', action: 'update', id: @board.id}, method: :put) do -%>
      <%= render 'form' -%>
    <%- end -%>
  </div>
</div>

app/views/boards/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1>The Board <small>Be Neighborly</small></h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <% if @user.skills_users.count > 0 %>
        <%= link_to "Add Request", new_board_path, class: 'btn btn-success', style: 'margin: 10px auto; margin-top: 0; float: none; display: block;' %>
      <% else %>
        <%= link_to 'Add Skill', skills_path, class: 'btn btn-success' %><mark>Add a skill to create a new barter request:</mark>
      <% end %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3>Filter Posts</h3>
        </div>
        <form action="">
        <ul class="list-group" style="margin: 0">
          <li class="list-group-item" style="border-radius: 0">
            <div class="form-group">
              <label for="skill_needed">Needing</label>
              <select name="skill_needed" id="skill_needed">
                <option value="none" selected>None</option>
                <%- for skill in @skills -%>
                  <option value="<%= skill -%>"><%= skill -%></option>
                <%- end -%>
              </select>
            </div>
          </li>
          <li class="list-group-item" style="border-radius: 0">
            <div class="form-group">
              <label for="skill_offered">Can Offer</label>
              <select name="skill_offered" id="skill_offered">
                <option value="none" selected>None</option>
                <%- for skill in @skills -%>
                  <option value="<%= skill -%>"><%= skill -%></option>
                <%- end -%>
              </select>
            </div>
          </li>
        </ul>
          <div class="panel-footer">
            <input type="submit" value="Filter" class="btn btn-primary" style="margin: 0 auto;display: block;"/>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-10">

      <div class="col-md-12">
        <div id="map-canvas" class="col-md-12 top-20" style="height: 300px; min-width: 500px; margin-top: 0"></div>
      </div>

      <div class="col-md-12">
        <table class="table table-hover">
          <thead>
          <tr>
            <th></th>
            <th>Needing</th>
            <th>Neighbor</th>
            <th>Can Offer</th>
            <th>Needed By</th>
          </tr>
          </thead>
          <tbody id="boards-table">
          <% @board.each do |b| -%>
            <tr id="board-<%= b.id -%>" class="">
              <td><%= link_to "View", board_path(b), class: "btn btn-info" -%></td>
              <td><% b.skill_needed.each do |skill| -%><%= skill -%> <%- end -%></td>
              <td><%= b.user.user_info.first_name -%></td>
              <td><% b.skills_offered.each do |skill| -%><%= skill -%>, <%- end -%></td>
              <td><%= b.needed_by.strftime("%D") -%></td>
            </tr>
          <%- end -%>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1>Create A Board Entry</h1>
      <p>Use this area to advertise the services and skills you are interested in bartering.</p>
      <p>The next page will allow you to explain the details of what you are looking for and services you can offer in exchange.  </p>
      <% if current_user.sign_in_count == 1 && current_user.boards.count == 0  %>
          <div class="alert alert-success" role="alert">Fill in the information below and click 'Submit' to continue.</div>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">

    <%= form_tag boards_path do -%>
    
    <%= render 'form' -%>
    <%- end -%>
  </div>
</div>

app/views/boards/show.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <h1><strong><%= @board.user.user_info.first_name -%></strong> needs <strong><%= @board.skill_needed[0] -%></strong> by <strong><%= @board.needed_by.strftime("%D") -%></strong> and can offer <strong><%= format_skills_offered @board.skills_offered -%></strong>.</h1>
      <%- if @board.user == current_user -%>
        <p>Use the message board below to communication with interested people.</p>
        <p>Use the handshake button to start an aggreement with someone.</p>
      <%- else -%>
        <p>Use this message board to discuss what is needed.</p>
      <%- end -%>
    </div>
    <%- if @user == @board.user -%>
    <div class="row">
      <div class="btn-group">
        <%= link_to "Edit", edit_board_path(@board), class: "btn btn-warning" -%>
        <%= link_to "Remove", board_path(@board), method: :delete, data: {confirm: "Are you sure you want to remove this?"}, class: "btn btn-danger" -%>
      </div>
    </div>
    <%- end -%>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= link_to "< The Board", boards_path, class: "board-heading" -%>
  </div>
  <div class="row">
    <%= react_component('Thread', {thread: @thread, messages: @messages, user_id: @user_id, user_name: @user_name, creator_id: @board.user.id, action_taken: (@board.agreements.to_a != [])}) -%>
  </div>
</div>