config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]

  get 'user_info/edit'

  post 'user_info/update'

  get 'addresses/get_user_address'

  get 'addresses/get_addresses_near_user'

  resources :boards
  resources :agreements, except: [:show]
  post 'agreements/:id/agree' => 'agreements#agree', as: :agreements_agree
  resources :message, only: [:new, :create, :destroy]

  authenticated :user do
    root :to => 'profile#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  get 'profile' => 'profile#index'

  post '/skill/add_skill_to_user' => 'skills#add_skill_to_user'
  post '/skill/kill_destroy' => 'skills#kill_destroy'
  delete '/skill/kill_destroy' => 'skills#kill_destroy'
  delete '/admin/destroy_user' => 'admin#destroy_user'
 
  post '/skill/create_skill' => 'skills#create_skill'

  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  scope :user do
    resources :skills do
      get 'delete'
    end
  end

  get 'kill' => 'skills#kill'
  get 'create_new_skill' => 'skills#create_new_skill'

  match ':controller(/:action(/:id))', :via => :get

end

app/models/agreement.rb
class Agreement < ActiveRecord::Base
  belongs_to :user
  belongs_to :board

  validates :user1skill, :user2skill, :due_date, :board_id, :user_id, presence: true
  validate :validates_user1skill
  validate :validates_user2skill
  validate :validates_due_date

  def validates_user1skill
    errors.add(:user1skill, :invalid) unless Skill.pluck(:name).include? user1skill
  end

  def validates_user2skill
    errors.add(:user2skill, :invalid) unless Skill.pluck(:name).include? user2skill
  end

  def validates_due_date
    errors.add(:due_date, :invalid) if due_date.past?
  end

  def user1
    self.board.user
  end

  def user2
    self.user
  end

end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController
  def index
    @agreements = Agreement.where(user: current_user)
  end

  # def show
  #   @agreement = Agreement.find(params[:id])
  #   @user1 = @agreement.board.user
  #   @user2 = @agreement.user
  #   @board = @agreement.board
  # end

  def new
    @agreement = Agreement.new
    @board = Board.find(params[:Board])
    @user1 = @board.user
    @user2 = User.find(params[:user2])
  end

  def create
    @agreement = Agreement.create(get_new_agreement_params)
    if @agreement.save
      redirect_to profile_path
    else
      redirect_to :back
    end
  end

  def edit
    @agreement = Agreement.find(params[:id])
    @board = @agreement.board
    @user1 = @board.user
    @user2 = @agreement.user
    @edit = true
  end

  def agree
    @agreement = Agreement.find(params[:id])
    if current_user == @agreement.board.user
      @agreement.user1_agrees = true
    elsif current_user == @agreement.user
      @agreement.user2_agrees = true
    end
    @agreement.save
    redirect_to profile_path
  end

  def update
    @agreement = Agreement.find(params[:id])
    unless @agreement.user1_agrees && @agreement.user2_agrees
      @agreement.details = params[:agreement][:details]
      @agreement.user1skill = params[:agreement][:user1skill]
      @agreement.user2skill = params[:agreement][:user2skill]
      @agreement.due_date = Date.new(params[:agreement][:due_date][:year].to_i, params[:agreement][:due_date][:month].to_i, params[:agreement][:due_date][:day].to_i)
      @agreement.user1_agrees = false
      @agreement.user2_agrees = false
      if @agreement.save
        redirect_to profile_path
      else
        redirect_to :back
      end
    else
      redirect_to profile_path
    end
  end

  def destroy
    @agreement = Agreement.find(params[:id])
    @agreement.status = 'deleted'
    redirect_to profile_path
  end

  private

  def get_new_agreement_params
    p = params.require(:agreement).permit(:user_id, :board_id, :details, :user1skill, :user2skill, due_date: [:year, :month, :day])
    {status: 'pending',user_id: p[:user_id], board_id: p[:board_id], details: p[:details], user1skill: p[:user1skill], user2skill: p[:user2skill], due_date: Date.new(p[:due_date][:year].to_i, p[:due_date][:month].to_i, p[:due_date][:day].to_i)}
  end

  def get_edit_agreement_params
    params.require(:agreement).permit(:details, :user1skill, :user2skill, due_date: [:year, :month, :day])
    {details: p[:details], user1skill: p[:user1skill], user2skill: p[:user2skill], due_date: Date.new(p[:due_date][:year].to_i, p[:due_date][:month].to_i, p[:due_date][:day].to_i)}
  end

end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/views/agreements/_destroy_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="destroyModal" tabindex="-1" role="dialog" aria-labelledby="destroyModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete Agreement</h4>
      </div>
      <div class="modal-body">
        <p>Delete Agreement?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to "Delete", agreement_path(@agreement), method: :delete, class: "btn btn-default" -%>
      </div>
    </div>
  </div>
</div>

app/views/agreements/_form.html.erb
<fieldset class="col-md-6">
  <legend>Agreement</legend>
  <input type="hidden" name="agreement[user_id]" value="<%= @user2.id -%>"/>
  <input type="hidden" name="agreement[board_id]" value="<%= @board.id -%>"/>
  <%- if current_page? new_agreement_path -%>

    <div class="form-group">
      <p>Date: <%= Date.today %></p>
      <div class="form-group">
        <label for="received_skill_id">Providing: <%= @user2.user_info.first_name %> <%= @user2.user_info.last_name %></label>
        <select name="agreement[user2skill]" id="received_skill_id" class="form-control">
          <option value="<%= @board.skill_needed[0] -%>"><%= @board.skill_needed[0] -%></option>
        </select>
      </div>
    </div>
    <div class="form-group">
      <label for="offered_skill_id">Skill you are providing: </label>
      <select name="agreement[user1skill]" id="offered_skill_id" class="form-control">
        <%- @board.skills_offered.each do |skill| -%>
          <option value="<%= skill -%>"><%= skill -%></option>
        <%- end -%>
      </select>
    </div>

  <%- else  -%>

    <%- if current_user == @agreement.board.user -%>
      <div class="form-group">
        <p>Date: <%= Date.today %></p>
        <div class="form-group">
          <label for="received_skill_id">Providing: <%= @user2.user_info.first_name %> <%= @user2.user_info.last_name %></label>
          <select name="agreement[user2skill]" id="received_skill_id" class="form-control">
            <option value="<%= @agreement.user2skill -%>"><%= @agreement.user2skill -%></option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label for="offered_skill_id">Skill you are providing: </label>
        <select name="agreement[user1skill]" id="offered_skill_id" class="form-control">
          <%- current_user.skills.pluck(:name).each do |skill| -%>
            <option value="<%= skill -%>" <%- if skill == @agreement.user1skill -%>selected<%- end -%>><%= skill -%></option>
          <%- end -%>
        </select>
      </div>
    <%- elsif current_user == @agreement.user -%>
      <div class="form-group">
        <p>Date: <%= Date.today %></p>
        <div class="form-group">
          <label for="received_skill_id">Providing: <%= @user1.user_info.first_name %> <%= @user1.user_info.last_name %></label>
          <select name="agreement[user1skill]" id="received_skill_id" class="form-control">
            <option value="<%= @agreement.user1skill -%>"><%= @agreement.user1skill -%></option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label for="offered_skill_id">Skill you are providing: </label>
        <select name="agreement[user2skill]" id="offered_skill_id" class="form-control">
          <%- current_user.skills.pluck(:name).each do |skill| -%>
            <option value="<%= skill -%>" <%- if skill == @agreement.user2skill -%>selected<%- end -%>><%= skill -%></option>
          <%- end -%>
        </select>
      </div>
    <%- end -%>

  <%- end -%>

  <div class="form-group">
    <label for="details">Details <br/><small>Location, directions, scope of work, etc.</small></label>
    <textarea name="agreement[details]" id="details" cols="30" rows="5" class="form-control"><%= @agreement.details -%></textarea>
  </div>
  <div class="form-group">
    <label for="name">Due Date</label>
    <%- if @agreement.id -%>
      <%= select_date @agreement.due_date, prefix: 'agreement[due_date]' -%>
    <%- else -%>
      <%= select_date @board.needed_by, prefix: 'agreement[due_date]' -%>
    <%- end -%>
  </div>
  <input type="hidden" name="status" value="pending">
  <div class="btn-group">
    <input value="Submit Proposed Agreement" class="btn btn-primary" type="submit"/>
    <%- if @edit -%>
      <%= link_to 'Agree', agreements_agree_path(@agreement), method: :post, class: 'btn btn-success' -%>
    <%- end -%>
  </div>
</fieldset>


<div class="col-md-6">
  <p style="font-size: 24px"><strong><%= @board.user.user_info.first_name -%></strong> needs <strong><%= @board.skill_needed[0] -%></strong> by <strong><%= @board.needed_by.strftime("%D") -%></strong><br/> and can offer <strong><%= format_skills_offered @board.skills_offered -%></strong>.</p>
  <p><strong>Location: </strong><%= @board.details['city'] -%></p>
  <p><strong>Contact Email: </strong><%= @board.details['email'] -%></p>
</div>

app/views/agreements/create.html.erb
<h1>Agreement#create</h1>
<p>Find me in app/views/agreement/create.html.erb</p>

app/views/agreements/destroy.html.erb
<h1>Agreement#destroy</h1>
<p>Find me in app/views/agreement/destroy.html.erb</p>

app/views/agreements/edit.html.erb
<div class="container">
  <div class="row top-70 bottom-30">
    <%= form_for @agreement, url: {action: "update"}, method: "PUT", html: {class: "update-agreement_form"} do |f| %>
      <%= render 'form' -%>
    <%- end -%>
  </div>
</div>

app/views/agreements/index.html.erb
<div class="container">
  <div>
    <h2>Agreements</h2>
  </div>

  <div class="row top-20">
    <% if @agreements.length > 0 %>
        <%- @agreements.each do |a| -%>
            <div class="col-md-4">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4><%= a.board.user.user_info.last_name %>, <%= a.board.user.user_info.first_name %></h4>
                  <h5>Skill: <%= a.user1skill %></h5>
                  <h4><%= a.user.user_info.last_name %>, <%= a.user.user_info.first_name %></h4>
                  <h5>Skill: <%= a.user2skill %></h5>
                </div>
                <div class="panel-body">
                  <strong>Status:</strong>
                  <%= a.status-%></br>
                  <strong>Due date:</strong>
                  <%= a.due_date-%>
                </div>
                <div class="panel-footer">
                  <div class="btn-group">
                    <%= link_to "View", agreement_path(a.id), class: "btn btn-default" -%>
                    <%= link_to "Edit", edit_agreement_path(a.id), class: "btn btn-default" -%>
                  </div>
                </div>
              </div>
            </div>
        <%- end -%>
     <% else %>
        <p>No Agreements Found</p>
    <% end %>
  </div>
</div>

app/views/agreements/new.html.erb
<div class="container" style="padding-top: 20px">
  <div class="row top-70 bottom-30">
    <%= form_for @agreement, url: {action: "create"}, html: {class: "create-agreement_form"} do |f| %>
        <%= render 'form' -%>
    <%- end -%>
  </div>
</div>

app/views/agreements/show.html.erb
<div class="container">
  <div class="row">
    <div class="btn-group">
      <%= link_to "View All", agreements_path, class: "btn btn-default", role: "button" -%>
    </div>
  </div>
  <div class="row top-40">
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3>Agreement:</h3>
            <h3><%= @agreement.board.user.user_info.last_name %>, <%= @agreement.board.user.user_info.first_name %></h3>
            <h4>Skill: <%= @agreement.user1skill %></h4>
            <h3><%= @agreement.user.user_info.last_name %>, <%= @agreement.user.user_info.first_name %></h3>
            <h4>Skill: <%= @agreement.user2skill %></h4>
          </div>
          <ul class="list-group">
            <li class="list-group-item" style="word-wrap:break-word;">
              <strong>Details:</strong>
              <%= @agreement.details-%>
            </li>
            <li class="list-group-item">
              <div>
                <strong>Status:</strong>
                <%= @agreement.status-%>
              </div>
              <div>
                <%= @agreement.board.user.user_info.first_name -%>: <%= @agreement.user1_agrees -%>
                <%= @agreement.user.user_info.first_name -%>: <%= @agreement.user2_agrees -%>
              </div>
            </li>
            <li class="list-group-item">
              <strong>Due date:</strong>
              <%= @agreement.due_date.strftime("%D")-%>
            </li>
          </ul>
        </div>
      </div>
  </div>
  <div class="btn-group">
    <%= link_to "Edit", edit_agreement_path(@agreement.id), class: "btn btn-default" -%>
    <button type="button" class="btn" data-toggle="modal" data-target="#destroyModal">Delete</button>

  </div>
</div>
<%= render "destroy_modal" -%>

app/views/agreements/update.html.erb
<h1>Agreement#update</h1>
<p>Find me in app/views/agreement/update.html.erb</p>